---
title: "Links"
---

<br>

### ***R* Resources**

[Using Plotly with *R*](https://plotly.com/r/){target="_blank"}<br>
Outstanding interactive plotting package (can integrate directly with `ggplot2` too)

[Using flexdashboard with *R*](https://rmarkdown.rstudio.com/flexdashboard/){target="_blank"}<br>
Sleek tool for building interactive dashboards (can also integrate with `shiny`)

[The *R* "Tidyverse"](https://tidyverse.org){target="_blank"}<br>
A collection of packages to streamline common *R* actions

[learnr](https://rstudio.github.io/learnr/){target="_blank"}<br>
A package that can be used to build *R* tutorials, quizzes, and other coding trainings

---

### **Other Resources**

[Connected Papers](https://connectedpapers.com){target="_blank"}<br>
Great website for conducting literature reviews, where a target article is used to generate a network diagram linking to other related papers in this research area (based on citation patterns)

---

### **Professional Organizations**

[International Association for Relationships Research (IARR)](https://iarr.org){target="_blank"}<br>
Interdisciplinary organization supporting the scientific study of social and personal relationships

[Society for Personality and Social Psychology (SPSP)](https://spsp.org){target="_blank"}<br>
Academic organization for personality and social psychologists

[Society for the Teaching of Psychology (STP)](https://teachpsych.org){target="_blank"}<br>
Division 2 of the American Psychological Association

[Association for Psychological Science (APS)](https://psychologicalscience.org){target="_blank"}<br>
Broad organization for psychological research, sponsoring journals, conferences, and grants

