---
title: "Teaching"
---

<br>

## **Instructor**

---

### *Johns Hopkins University*

**Psychology and Social Media** <br> *Summer 2018 -- Present* <br>
A new class I developed covering the intersection between psychological processes and digital social media phenomena (e.g., motivation, norms, group processes, mental health) 

**Research Methods in Psychology** <br> *Fall 2017 -- Present* <br>
The first class in a two-course sequence on research methods, data management, and applied statistics (with data collection and analysis lab)

**Design and Statistical Analysis for Psychology** <br> *Spring 2018 -- Present* <br>
The second class in a two-course sequence on research methods, data management, and applied statistics (with data collection and analysis lab)

**Advanced Statistical Methods** <br> *Fall 2017 -- Present* <br>
A first-semester statistics class for first-year Ph.D. students in Psychological and Brain Sciences

**Advanced Research Design and Analysis** <br> *Spring 2018 -- Present* <br>
A second-semester statistics class for first-year Ph.D. students in Psychological and Brain Sciences

---

### *University of California, Santa Barbara*

**Introduction to Statistics** <br> *Spring 2017* <br>
An undergraduate course on statistics for psychology majors

**Introduction to Experimental Psychology** <br> *Summer 2016* <br>
An undergraduate course on research methods and experimental design

**Positive Psychology** <br> *Summer 2015* <br>
An upper-level undergraduate course covering topics such as self-esteem, character strengths, mental health, intimate relationships, and positive emotion

**Social Psychology of Close Relationships** <br> *Summer 2014* <br>
An upper-level undergraduate course covering a range of theoretical perspectives on the study of interpersonal relationships

---

## **Worskshop Leader**

---

### *University of California, Santa Barbara*

**Dyadic Data Analysis** <br> *Fall 2015* <br>
A workshop for Ph.D. students covering multilevel analytic techniques for use in the study of related pairs of observations

**Summer Teaching Institute for Associates** <br> *Summer 2015 -- Summer 2016* <br>
Facilitation of multiple pedagogical and instructional design workshops for first-time instructors, designed for Ph.D. students in the social sciences

---

## **Teaching Assistant**

---

### *University of California, Santa Barbara*

**Advanced Research Methods Lab** <br> *Fall 2016* <br>
Hands-on lab course in experimental methods (including original data collection) for upper-level undergraduates

**Health Psychology** <br> *Summer 2013* <br>
Survey course in topics such as biopsychology, health behavior change, and stress

**Introduction to Social Psychology** <br> *Spring 2013* <br>
Survey course in social psychological topics (e.g., intergroup processes, culture, self, social cognition, motivation, and relationships)

**Introduction to Psychology** <br> *Spring 2012 -- Summer 2012* <br>
Introductory course exposing lower-level undergraduates to the field of psychology

**Social Psychology of Close Relationships** <br> *Fall 2011 -- Summer 2012* <br>
An upper-level undergraduate course covering a range of theoretical perspectives on the study of interpersonal relationships

**Introduction to Statistics** <br> *Winter 2012* <br>
An undergraduate course on statistics for psychology majors

---

### *Cornell University*

**Language Development** <br> *Spring 2011* <br>
An upper-level undergraduate lab course covering methods of data collection in developmental psycholinguistics and research on language acquisition

---

